# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.28.0'
    - name: Run application
          working-directory: src
          run: |
            docker-compose up -d
