# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.28.0'
    - name: Install openconnect client
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y openconnect
    - name: Run application
      working-directory: src
      run: docker-compose up -d
    - name: Create VPN user
      run: docker exec openconnect ocpasswd -c /config/ocpasswd markusmcnugen

    - name: Try to connect via openconnect to public IP
      run: openconnect https://localhost/

    - name: Save logs to file
      if: always()
      working-directory: src
      run: docker-compose logs --no-color |& tee logs.txt
    - uses: actions/upload-artifact@v2
      name: Archive logs
      if: always()
      with:
        name: logs
        path: ./src/logs.txt
